services:
  cactus:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfiles/Cactus/Dockerfile
    volumes:
    - type: bind
      source: ./results
      target: /results
    - type: bind
      source: ./input_data
      target: /input_data
    command:
    - /bin/bash
    - -c
    - mkdir -p /results && cactus --help > /results/cactus_help.txt 2>&1
  minigraph:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfiles/Minigraph/Dockerfile
    volumes:
    - type: bind
      source: ./results
      target: /results
    - type: bind
      source: ./input_data
      target: /input_data
    command:
    - /bin/bash
    - -c
    - mkdir -p /results && cd /minigraph && ./minigraph > /results/minigraph_help.txt
      2>&1 || true
  minigraphcactus:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfiles/MinigraphCactus/Dockerfile
    volumes:
    - type: bind
      source: ./results
      target: /results
    - type: bind
      source: ./input_data
      target: /input_data
    command:
    - /bin/bash
    - -c
    - mkdir -p /results && cactus-pangenome --help > /results/minigraphcactus_help.txt
      2>&1
  pggb:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfiles/PGGB/Dockerfile
    volumes:
    - type: bind
      source: ./results
      target: /results
    - type: bind
      source: ./input_data
      target: /input_data
    command:
    - /bin/bash
    - -c
    - mkdir -p /results && pggb --help > /results/pggb_help.txt 2>&1 || true
  progressivecactus:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfiles/ProgressiveCactus/Dockerfile
    volumes:
    - type: bind
      source: ./results
      target: /results
    - type: bind
      source: ./input_data
      target: /input_data
    command:
    - /bin/bash
    - -c
    - mkdir -p /results && cactus --help > /results/progressivecactus_help.txt 2>&1
  theseus:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfiles/Theseus/Dockerfile
    volumes:
    - type: bind
      source: ./results
      target: /results
    - type: bind
      source: ./input_data
      target: /input_data
    command:
    - /bin/bash
    - -c
    - mkdir -p /results && theseus_msa > /results/theseus_help.txt 2>&1 ||
      true
  poasta:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfiles/POASTA/Dockerfile
    volumes:
    - type: bind
      source: ./results
      target: /results
    - type: bind
      source: ./input_data
      target: /input_data
    command:
    - /bin/bash
    - -c
    - mkdir -p /results && poasta align --help > /results/poasta_help.txt 2>&1 ||
      true
  lcpan:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfiles/LCPan/Dockerfile
    volumes:
    - type: bind
      source: ./results
      target: /results
    - type: bind
      source: ./input_data
      target: /input_data
    command:
    - /bin/bash
    - -c
    - mkdir -p /results && /lcpan/bin/lcpan --help > /results/lcpan_help.txt 2>&1
      || true
