Cactus:
  source: image
  ref: v3.1.4

Minigraph:
  source: git
  ref: v0.21

MinigraphCactus:
  source: image
  ref: v3.1.4

PGGB:
  source: image
  ref: sha256:08bd929d8b60270719449434308fe78965f4567c45b35ea1a9558f2ee3004cc0

ProgressiveCactus:
  source: image
  ref: v3.1.4

Theseus:
  source: git
  ref: v0.1

LCPan:                        
  source: git
  ref: v1.1
